services:
  _defaults:
    public: true

  kaudaj.module.dbvcs.version_control_manager:
    class: Kaudaj\Module\DBVCS\Utils\VersionControlManager
    arguments:
      - "@prestashop.core.command_bus"

  kaudaj.module.dbvcs.file_parser:
    class: Kaudaj\Module\DBVCS\Utils\FileParser

  kaudaj.module.dbvcs.form.settings.general_configuration:
    class: Kaudaj\Module\DBVCS\Form\Settings\GeneralConfiguration
    arguments:
      - "@prestashop.adapter.legacy.configuration"
      - "@prestashop.adapter.shop.context"
      - "@prestashop.adapter.multistore_feature"

  kaudaj.module.dbvcs.form.settings.general_type:
    class: 'Kaudaj\Module\DBVCS\Form\Settings\GeneralType'
    parent: "form.type.translatable.aware"
    public: true
    tags:
      - { name: form.type }

  kaudaj.module.dbvcs.form.settings.general_form_data_provider:
    class: 'Kaudaj\Module\DBVCS\Form\Settings\GeneralFormDataProvider'
    arguments:
      - "@kaudaj.module.dbvcs.form.settings.general_configuration"

  kaudaj.module.dbvcs.form.settings.general_form_data_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\Handler'
    arguments:
      - "@form.factory"
      - "@prestashop.core.hook.dispatcher"
      - "@kaudaj.module.dbvcs.form.settings.general_form_data_provider"
      - 'Kaudaj\Module\DBVCS\Form\Settings\GeneralType'
      - "General"

  kaudaj.module.dbvcs.form.settings.changes_registration.configuration:
    class: Kaudaj\Module\DBVCS\Form\Settings\ChangesRegistration\ChangesRegistrationConfiguration
    arguments:
      - '@prestashop.adapter.legacy.configuration'
      - '@prestashop.adapter.shop.context'
      - '@prestashop.adapter.multistore_feature'
      - '@=service("prestashop.adapter.legacy.context").getContext().cookie'
      - '@=service("prestashop.adapter.environment").isDebug()'

  kaudaj.module.dbvcs.form.settings.changes_registration.type:
    class: 'Kaudaj\Module\DBVCS\Form\Settings\ChangesRegistration\ChangesRegistrationType'
    parent: "form.type.translatable.aware"
    public: true
    tags:
      - { name: form.type }

  kaudaj.module.dbvcs.form.settings.changes_registration.form_data_provider:
    class: Kaudaj\Module\DBVCS\Form\Settings\ChangesRegistration\ChangesRegistrationFormDataProvider
    arguments:
      - '@kaudaj.module.dbvcs.form.settings.changes_registration.configuration'

  kaudaj.module.dbvcs.form.settings.changes_registration.form_data_handler:
    class: PrestaShop\PrestaShop\Core\Form\Handler
    arguments:
      - '@form.factory'
      - '@prestashop.core.hook.dispatcher'
      - '@kaudaj.module.dbvcs.form.settings.changes_registration.form_data_provider'
      - 'Kaudaj\Module\DBVCS\Form\Settings\ChangesRegistration\ChangesRegistrationType'
      - ChangesRegistration

  kaudaj.module.dbvcs.change.query_handler.abstract:
    abstract: true
    class: Kaudaj\Module\DBVCS\Domain\Change\QueryHandler\AbstractChangeQueryHandler
    arguments:
      - '@doctrine.orm.entity_manager'

  kaudaj.module.dbvcs.change.query_handler.get:
    public: true
    parent: 'kaudaj.module.dbvcs.change.query_handler.abstract'
    class: Kaudaj\Module\DBVCS\Domain\Change\QueryHandler\GetChangeHandler
    tags:
      - name: tactician.handler
        command: Kaudaj\Module\DBVCS\Domain\Change\Query\GetChange

  kaudaj.module.dbvcs.change.command_handler.abstract:
    abstract: true
    class: Kaudaj\Module\DBVCS\Domain\Change\CommandHandler\AbstractChangeCommandHandler
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@prestashop.core.admin.lang.repository'
      - '@prestashop.core.admin.shop.repository'
      - '@prestashop.core.admin.shop_group.repository'

  kaudaj.module.dbvcs.change.command_handler.add:
    public: true
    parent: 'kaudaj.module.dbvcs.change.command_handler.abstract'
    class: Kaudaj\Module\DBVCS\Domain\Change\CommandHandler\AddChangeHandler
    tags:
      - name: tactician.handler
        command: Kaudaj\Module\DBVCS\Domain\Change\Command\AddChangeCommand

  kaudaj.module.dbvcs.change.command_handler.edit:
    public: true
    parent: 'kaudaj.module.dbvcs.change.command_handler.abstract'
    class: Kaudaj\Module\DBVCS\Domain\Change\CommandHandler\EditChangeHandler
    tags:
      - name: tactician.handler
        command: Kaudaj\Module\DBVCS\Domain\Change\Command\EditChangeCommand

  kaudaj.module.dbvcs.change.command_handler.delete:
    public: true
    parent: 'kaudaj.module.dbvcs.change.command_handler.abstract'
    class: Kaudaj\Module\DBVCS\Domain\Commit\CommandHandler\DeleteChangeHandler
    tags:
      - name: tactician.handler
        command: Kaudaj\Module\DBVCS\Domain\Commit\Command\DeleteChangeCommand

  kaudaj.module.dbvcs.commit.query_handler.abstract:
    abstract: true
    class: Kaudaj\Module\DBVCS\Domain\Commit\QueryHandler\AbstractCommitQueryHandler
    arguments:
      - '@doctrine.orm.entity_manager'

  kaudaj.module.dbvcs.commit.query_handler.get:
    public: true
    parent: 'kaudaj.module.dbvcs.commit.query_handler.abstract'
    class: Kaudaj\Module\DBVCS\Domain\Commit\QueryHandler\GetCommitHandler
    tags:
      - name: tactician.handler
        command: Kaudaj\Module\DBVCS\Domain\Commit\Query\GetCommit

  kaudaj.module.dbvcs.commit.command_handler.abstract:
    abstract: true
    class: Kaudaj\Module\DBVCS\Domain\Commit\CommandHandler\AbstractCommitCommandHandler
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@prestashop.core.admin.lang.repository'
      - '@prestashop.core.admin.shop.repository'
      - '@prestashop.core.admin.shop_group.repository'

  kaudaj.module.dbvcs.commit.command_handler.add:
    public: true
    parent: 'kaudaj.module.dbvcs.commit.command_handler.abstract'
    class: Kaudaj\Module\DBVCS\Domain\Commit\CommandHandler\AddCommitHandler
    tags:
      - name: tactician.handler
        command: Kaudaj\Module\DBVCS\Domain\Commit\Command\AddCommitCommand

  kaudaj.module.dbvcs.commit.command_handler.edit:
    public: true
    parent: 'kaudaj.module.dbvcs.commit.command_handler.abstract'
    class: Kaudaj\Module\DBVCS\Domain\Commit\CommandHandler\EditCommitHandler
    tags:
      - name: tactician.handler
        command: Kaudaj\Module\DBVCS\Domain\Commit\Command\EditCommitCommand

  kaudaj.module.dbvcs.commit.command_handler.delete:
    public: true
    parent: 'kaudaj.module.dbvcs.commit.command_handler.abstract'
    class: Kaudaj\Module\DBVCS\Domain\Commit\CommandHandler\DeleteCommitHandler
    tags:
      - name: tactician.handler
        command: Kaudaj\Module\DBVCS\Domain\Commit\Command\DeleteCommitCommand
  
  kaudaj.module.dbvcs.grid.definition.factory.change_grid_definition_factory:
    public: true
    class: Kaudaj\Module\DBVCS\Grid\Definition\Factory\ChangeGridDefinitionFactory
    parent: prestashop.core.grid.definition.factory.abstract_grid_definition

  kaudaj.module.dbvcs.grid.query.change_query_builder:
    public: true
    class: Kaudaj\Module\DBVCS\Grid\Query\ChangeQueryBuilder
    parent: prestashop.core.grid.abstract_query_builder
    arguments:
      - '@=service("prestashop.adapter.legacy.context").getContext().language.id'
      - '@prestashop.adapter.shop.context'

  kaudaj.module.dbvcs.grid.data.factory.change_data_factory:
    public: true
    class: PrestaShop\PrestaShop\Core\Grid\Data\Factory\DoctrineGridDataFactory
    arguments:
      - '@kaudaj.module.dbvcs.grid.query.change_query_builder'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.core.grid.query.doctrine_query_parser'
      - changes

  kaudaj.module.dbvcs.grid.change_grid_factory:
    public: true
    class: PrestaShop\PrestaShop\Core\Grid\GridFactory
    arguments:
      - '@kaudaj.module.dbvcs.grid.definition.factory.change_grid_definition_factory'
      - '@kaudaj.module.dbvcs.grid.data.factory.change_data_factory'
      - '@prestashop.core.grid.filter.form_factory'
      - '@prestashop.core.hook.dispatcher'
  
  kaudaj.module.dbvcs.command.commit:
    class: Kaudaj\Module\DBVCS\Command\CommitCommand
    arguments:
      - '@kaudaj.module.dbvcs.version_control_manager'
      - "@prestashop.core.command_bus"
    tags:
      - { name: 'console.command' }
