services:
  _defaults:
    public: true

  kaudaj.module.dbvcs.version_control_manager:
    class: Kaudaj\Module\DBVCS\VersionControlManager

  kaudaj.module.dbvcs.form.settings.general_configuration:
    class: Kaudaj\Module\DBVCS\Form\Settings\GeneralConfiguration
    arguments:
      - "@prestashop.adapter.legacy.configuration"
      - "@prestashop.adapter.shop.context"
      - "@prestashop.adapter.multistore_feature"

  kaudaj.module.dbvcs.form.settings.general_type:
    class: 'Kaudaj\Module\DBVCS\Form\Settings\GeneralType'
    parent: "form.type.translatable.aware"
    public: true
    tags:
      - { name: form.type }

  kaudaj.module.dbvcs.form.settings.general_form_data_provider:
    class: 'Kaudaj\Module\DBVCS\Form\Settings\GeneralFormDataProvider'
    arguments:
      - "@kaudaj.module.dbvcs.form.settings.general_configuration"

  kaudaj.module.dbvcs.form.settings.general_form_data_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\Handler'
    arguments:
      - "@form.factory"
      - "@prestashop.core.hook.dispatcher"
      - "@kaudaj.module.dbvcs.form.settings.general_form_data_provider"
      - 'Kaudaj\Module\DBVCS\Form\Settings\GeneralType'
      - "General"

  kaudaj.module.dbvcs.change.query_handler.abstract:
    abstract: true
    class: Kaudaj\Module\DBVCS\Domain\Change\QueryHandler\AbstractChangeQueryHandler
    arguments:
      - '@doctrine.orm.entity_manager'

  kaudaj.module.dbvcs.change.query_handler.get:
    public: true
    parent: 'kaudaj.module.dbvcs.change.query_handler.abstract'
    class: Kaudaj\Module\DBVCS\Domain\Change\QueryHandler\GetChangeHandler
    tags:
      name: tactician.handler
      command: Kaudaj\Module\DBVCS\Domain\Change\Query\GetChangeForEditing

  kaudaj.module.dbvcs.change.command_handler.abstract:
    abstract: true
    class: Kaudaj\Module\DBVCS\Domain\Change\CommandHandler\AbstractChangeCommandHandler
    arguments:
      - '@doctrine.orm.entity_manager'

  kaudaj.module.dbvcs.change.command_handler.add:
    public: true
    parent: 'kaudaj.module.dbvcs.change.command_handler.abstract'
    class: Kaudaj\Module\DBVCS\Domain\Change\CommandHandler\AddChangeHandler
    tags:
      name: tactician.handler
      command: Kaudaj\Module\DBVCS\Domain\Change\Command\AddChangeCommand

  kaudaj.module.dbvcs.change.command_handler.edit:
    public: true
    parent: 'kaudaj.module.dbvcs.change.command_handler.abstract'
    class: Kaudaj\Module\DBVCS\Domain\Change\CommandHandler\EditChangeHandler
    tags:
      name: tactician.handler
      command: Kaudaj\Module\DBVCS\Domain\Change\Command\EditChangeCommand

  kaudaj.module.dbvcs.change.command_handler.delete:
    public: true
    parent: 'kaudaj.module.dbvcs.change.command_handler.abstract'
    class: Kaudaj\Module\DBVCS\Domain\Change\CommandHandler\DeleteChangeHandler
    tags:
      name: tactician.handler
      command: Kaudaj\Module\DBVCS\Domain\Change\Command\DeleteChangeCommand
  
  kaudaj.module.dbvcs.grid.definition.factory.change_grid_definition_factory:
    public: true
    class: Kaudaj\Module\DBVCS\Grid\Definition\Factory\ChangeGridDefinitionFactory
    parent: prestashop.core.grid.definition.factory.abstract_grid_definition

  kaudaj.module.dbvcs.grid.query.change_query_builder:
    public: true
    class: Kaudaj\Module\DBVCS\Grid\Query\ChangeQueryBuilder
    parent: prestashop.core.grid.abstract_query_builder
    arguments:
      - '@=service("prestashop.adapter.legacy.context").getContext().language.id'
      - '@=service("prestashop.adapter.legacy.context").getContext().shop.id'

  kaudaj.module.dbvcs.grid.data.factory.change_data_factory:
    public: true
    class: PrestaShop\PrestaShop\Core\Grid\Data\Factory\DoctrineGridDataFactory
    arguments:
      - '@kaudaj.module.dbvcs.grid.query.change_query_builder'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.core.grid.query.doctrine_query_parser'
      - changes

  kaudaj.module.dbvcs.grid.change_grid_factory:
    public: true
    class: PrestaShop\PrestaShop\Core\Grid\GridFactory
    arguments:
      - '@kaudaj.module.dbvcs.grid.definition.factory.change_grid_definition_factory'
      - '@kaudaj.module.dbvcs.grid.data.factory.change_data_factory'
      - '@prestashop.core.grid.filter.form_factory'
      - '@prestashop.core.hook.dispatcher'
